### Basic Config

# MATEKSYS FC on CineRat 3inch Race Quad (and simuation model)
#TARGET = STM32H743
#EXTRA_FLAGS = -D'BUILD_KEY=4880cd41e59e44642e41c3f6344b3993' -D'RELEASE_NAME=4.4.2' -D'BOARD_NAME=MATEKH743' -D'MANUFACTURER_ID=MTKS' -DCLOUD_BUILD -DUSE_GYRO -DUSE_GYRO_SPI_ICM42605 -DUSE_GYRO_SPI_ICM42688P -DUSE_GYRO_SPI_MPU6000 -DUSE_GYRO_SPI_MPU6500 -DUSE_ACC -DUSE_ACC_SPI_ICM42605 -DUSE_ACC_SPI_ICM42688P -DUSE_ACC_SPI_MPU6000 -DUSE_ACC_SPI_MPU6500 -DUSE_DSHOT -DUSE_LED_STRIP -DUSE_MAX7456 -DUSE_OSD -DUSE_OSD_HD -DUSE_OSD_SD -DUSE_PINIO -DUSE_BLACKBOX -DUSE_SDCARD -DUSE_SERIALRX -DUSE_SERIALRX_SBUS -DUSE_SERIALRX_CRSF -DUSE_TELEMETRY -DUSE_TELEMETRY_SMARTPORT

# Trashcan
#EXTRA_FLAGS = -D'BUILD_KEY=8af98ed87422efa3d2eff0e2e7a86e80' -D'RELEASE_NAME=4.4.2' -D'BOARD_NAME=CRAZYBEEF4FR' -D'MANUFACTURER_ID=HAMO' -DCLOUD_BUILD -DUSE_GYRO -DUSE_GYRO_SPI_ICM20689 -DUSE_GYRO_SPI_ICM42688P -DUSE_GYRO_SPI_MPU6000 -DUSE_ACC -DUSE_ACC_SPI_ICM20689 -DUSE_ACC_SPI_ICM42688P -DUSE_ACC_SPI_MPU6000 -DUSE_ACCGYRO_BMI270 -DUSE_DSHOT -DUSE_GPS -DUSE_LED_STRIP -DUSE_MAX7456 -DUSE_OSD -DUSE_OSD_HD -DUSE_OSD_SD -DUSE_PINIO -DUSE_RX_CC2500 -DUSE_RX_SPI -DUSE_SERIALRX -DUSE_SERIALRX_CRSF -DUSE_SERIALRX_DEFAULT -DUSE_SERIALRX_GHST -DUSE_SERIALRX_SBUS -DUSE_TELEMETRY -DUSE_TELEMETRY_CRSF -DUSE_TELEMETRY_GHST -DUSE_TELEMETRY_SMARTPORT -DUSE_VTX -DUSE_BLACKBOX
#TARGET = STM32F411

# some random f7
#TARGET = STM32F7X2
#EXTRA_FLAGS = -D'BUILD_KEY=4880cd41e59e44642e41c3f6344b3993' -D'RELEASE_NAME=4.4.2' -D'BOARD_NAME=SPEEDYBEEF7' -D'MANUFACTURER_ID=SPDB' -DCLOUD_BUILD -DUSE_GYRO -DUSE_GYRO_SPI_ICM42605 -DUSE_GYRO_SPI_ICM42688P -DUSE_GYRO_SPI_MPU6000 -DUSE_GYRO_SPI_MPU6500 -DUSE_ACC -DUSE_ACC_SPI_ICM42605 -DUSE_ACC_SPI_ICM42688P -DUSE_ACC_SPI_MPU6000 -DUSE_ACC_SPI_MPU6500 -DUSE_DSHOT -DUSE_GPS -DUSE_LED_STRIP -DUSE_MAX7456 -DUSE_OSD -DUSE_OSD_HD -DUSE_OSD_SD -DUSE_PINIO -DUSE_BLACKBOX -DUSE_SDCARD -DUSE_SERIALRX -DUSE_SERIALRX_SBUS -DUSE_SERIALRX_CRSF -DUSE_TELEMETRY -DUSE_TELEMETRY_SMARTPORT

#TARGET = SITL
#EXTRA_FLAGS = -Wno-double-promotion -Wno-misleading-indentation# miss me with that s
#EXTRA_FLAGS += -DUSE_IMU_CALC -DUSE_ACC -DUSE_FAKE_ACC -DUSE_GYRO -DUSE_FAKE_GYRO

TARGET = MOCKUP
EXTRA_FLAGS = -Wno-double-promotion -Wno-misleading-indentation# miss me with that s
EXTRA_FLAGS += -DUSE_IMU_CALC -DUSE_ACC -DUSE_FAKE_ACC -DUSE_GYRO -DUSE_FAKE_GYRO -DUSE_GPS_PI
EXTRA_FLAGS += -DUSE_BLACKBOX


### Developer options
#EXTRA_FLAGS += -fstack-usage -Wstack-usage=1024 # WARNING: only works with DEBUG=GDB
#EXTRA_FLAGS += -fanalyzer -fdump-analyzer-callgraph #-fdump-analyzer-supergraph -fdump-analyzer-exploded-graph#-fdump-rtl-all-graph#
#EXTRA_FLAGS += -DUSE_CLI_DEBUG_PRINT
EXTRA_FLAGS += -ggdb3 -gdwarf-5 -frecord-gcc-switches # get debug symbols even when compiling with optimisations
EXTRA_FLAGS += -frecord-gcc-switches
#EXTRA_FLAGS += -DUSE_BENCHMARK
#EXTRA_FLAGS += -DUSE_STACK_CHECK

### Extra Options

# indi config:
EXTRA_FLAGS += -DUSE_INDI

# telemetry config:
EXTRA_FLAGS += -DUSE_TELEMETRY -DUSE_TELEMETRY_PI -DPI_STATS -DPI_USE_PRINT_MSGS
EXTRA_FLAGS += -DUSE_GPS_PI
#EXTRA_FLAGS += -DUSE_LOCAL_POSITION_PI

# run EKF and whether to use it as vehicle state whenever position mode is active
# WARNING: USE_EKF_* are untested, and doubtful especially with inflight switching between POSITION and manual flying
EXTRA_FLAGS += -DUSE_EKF
#EXTRA_FLAGS += -DUSE_EKF_POSITION -DUSE_EKF_ATTITUDE # TODO: convert to settings! Edit: they are now settings

# higher level controllers
#EXTRA_FLAGS += -DUSE_LOCAL_POSITION # controller and receivers/estimators. replaces USE_POS_CTL and USE_VEL_CTL
EXTRA_FLAGS += -DUSE_POS_CTL -DUSE_VEL_CTL
#EXTRA_FLAGS += -DUSE_GPS
EXTRA_FLAGS += -DUSE_TRAJECTORY_TRACKER

# also notch filter accelerometer 
#EXTRA_FLAGS += -DUSE_ACCEL_RPM_FILTER 

# DANGEROUS modes!!
EXTRA_FLAGS += -DUSE_THROW_TO_ARM
EXTRA_FLAGS += -DUSE_THROWING_WITHOUT_POSITION
EXTRA_FLAGS += -DUSE_CATAPULT
EXTRA_FLAGS += -DUSE_LEARNER
EXTRA_FLAGS += -DUSE_NN_CONTROL

# Remove propellers: hardware in the loop simulation over UART
#EXTRA_FLAGS += -DHIL_BUILD
