### Basic Config

TARGET = MOCKUP
EXTRA_FLAGS = -Wno-double-promotion -Wno-misleading-indentation
EXTRA_FLAGS += -DUSE_IMU_CALC -DUSE_ACC -DUSE_FAKE_ACC -DUSE_GYRO -DUSE_FAKE_GYRO -DUSE_BLACKBOX

########## FURTHER OPTIONS
# Developer options
#EXTRA_FLAGS += -DUSE_BENCHMARK -DUSE_STACK_CHECK

# indi config:
EXTRA_FLAGS += -DUSE_INDI

# telemetry config:
EXTRA_FLAGS += -DUSE_TELEMETRY -DUSE_TELEMETRY_PI -DPI_STATS -DPI_USE_PRINT_MSGS -DUSE_GPS_PI

# higher level controllers / estimators
EXTRA_FLAGS += -DUSE_EKF
EXTRA_FLAGS += -DUSE_POS_CTL -DUSE_VEL_CTL
EXTRA_FLAGS += -DUSE_GPS
EXTRA_FLAGS += -DUSE_TRAJECTORY_TRACKER

# DANGEROUS modes!!
#EXTRA_FLAGS += -DUSE_ACCEL_RPM_FILTER 
EXTRA_FLAGS += -DUSE_THROW_TO_ARM -DUSE_THROWING_WITHOUT_POSITION
EXTRA_FLAGS += -DUSE_CATAPULT
EXTRA_FLAGS += -DUSE_LEARNER
EXTRA_FLAGS += -DUSE_NN_CONTROL
